#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

sudo apt update
sudo apt install -y build-essential make

BASHMARK_DIR="bashmarks"
git -C "${BASHMARK_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${BASHMARK_DIR}"
cd "${BASEDIR}/${BASHMARK_DIR}"
make install
